config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  resources :recipes do
    resource :favorites, only: [:create, :index, :destroy]
  end

  resources :menus, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "menus/destroy_all" => "menus#destroy_all"

  resources :histories, only:[:index, :show]
  resources :ingredients, only:[:index]

  resources :users, only:[:show, :edit, :update]
  resources :recipe_ings, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "recipe_ings/destroy_all" => "recipe_ings#destroy_all"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  has_many :favorite_recipes, through: :favorites, source: 'recipe'

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user, dependent: :destroy

  belongs_to :menu, dependent: :destroy


end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ings, dependent: :destroy
  has_many :recipes
  has_many :histories, dependent: :destroy

end

app/models/menu.rb
class Menu < ApplicationRecord

  attribute :quantity, :integer,  default: '1'

  belongs_to :user
  belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :user

  has_many :menus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_ings, dependent: :destroy
  has_many :ingredints, through: :recipe_ings, source: 'Ingredient'

  has_many :favorite_users, through: :favorites, source: 'User'

  attachment :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recipe_ing.rb
class RecipeIng < ApplicationRecord

  attribute :quantity, :integer,  default: '1'

  belongs_to :user
  belongs_to :ingredient
  belongs_to :recipe

  def sum_of_ing_cal
    ingredient.ing_cal * quantity
  end

  def sum_of_ing_protein
    ingredient.ing_protein * quantity
  end

  def sum_of_ing_fat
    ingredient.ing_fat * quantity
  end

  def sum_of_ing_carbon
    ingredient.ing_carbon * quantity
  end

  def sum_of_ing_salt
    ingredient.ing_salt * quantity
  end

  def sum_of_ing_vit_b1
    ingredient.ing_vit_b1 * quantity
  end

  def sum_of_ing_vit_b2
    ingredient.ing_vit_b2 * quantity
  end

  def sum_of_ing_vit_c
    ingredient.ing_vit_c * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :menus
  has_many :histories, dependent: :destroy
  has_many :user_infos, dependent: :destroy
  has_many :recipe_ings, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :birthday, presence: true

end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.new(recipe_id: recipe.id)
    favorite.save
    redirect_to recipe_path(recipe)
  end

  def index
    @facorite_recipes = current_user.favorite_recipes
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    favorite = current_user.favorites.find_by(recipe_id: recipe.id)
    favorite.destroy
    redirect_to recipe_path(recipe)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes = Recipe.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!

  def index
    @menus = Menu.all
    @history = History.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.user_id = current_user.id

    if current_user.menus.find_by(recipe_id: params[:menu][:recipe_id]).present?
      @menu = current_user.menus.find_by(recipe_id: params[:menu][:recipe_id])
      @menu.quantity += params[:menu][:quantity].to_i
      @menu.save
      redirect_to menus_path

    else
      @menu.save
      redirect_to menus_path
    end
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(quantity: params[:quantity])
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end


  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_path(menu_id: params[:menu_id])
  end

  private

  def menu_params
    params.require(:menu).permit(:recipe_id, :quantity)

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @menu = Menu.new
    @user = current_user
    @recipe_ings = @recipe.recipe_ings
    # @recipe.cal = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_cal }
    # @recipe.protein = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_protein }
    # @recipe.fat = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_fat }
    # @recipe.carbon = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_carbon }
    # @recipe.salt = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_salt }
    # @recipe.vit_b1 = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_b1 }
    # @recipe.vit_b2 = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_b2 }
    # @recipe.vit_c = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_c }
  end

  def new
    @recipe = Recipe.new
    @user = current_user
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "新しいレシピが登録されました"
    else
      flash.now[:alert] = 'レシピの新規登録に失敗しました。'
      render "new"
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:image, :name, :explanation, :cal, :protein, :fat, :carbon, :salt, :vit_b1, :vit_b2, :vit_c)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @recipes = current_user.recipes
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if current_user.update(user_params)
      redirect_to user_path(@user), notice: "内容を変更しました"
    else
      render "edit"
    end
  end

  def user_params
    params.require(:user).permit(:name, :birthday, :gender,)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/recipe_ings_helper.rb
module RecipeIngsHelper
  def calc_nutrition(quantity, nutrition)
    if quantity.present? && nutrition.present?
      (quantity * nutrition).to_s(:delimited)
    else
      "0"
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if @recipe.favorited_by?(current_user) %>
    <p>
      <%= link_to recipe_favorites_path(@recipe), method: :delete do %>
        ♥<%= @recipe.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to recipe_favorites_path(@recipe), method: :post do %>
        ♡<%= @recipe.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/favorites/index.html.erb
<div class="container">
  <h4 class = "col-3 text-center" style = "background-color:lightgray">お気に入り一覧</h4>
  <div class="d-flex flex-wrap">
    <% @recipes.each do |recipe| %>
      <% if recipe.recipe_ings.present? %>
      <div class="col-md-3">
        <div class="card">
          <div class="col-xs-3" style="padding-right: 0px; padding-left: 0px;">
            <%= link_to recipe_path(recipe.id, recipe_ing) ,style: "color: black;", data: {"turbolinks" => false} do %>
              <%= attachment_image_tag recipe, :image, format: 'jpeg', size: "248x200"%><br>
              <%= recipe.name %><br>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/menus/index.html.erb
<% if !@menus.present? %>

  <div class="container">
      <div class= "row py-3 px-5">
    <div class= "text-start design">
      <h2 style= "background-color:lightgray">今日の献立</h2>
    </div>
    <div class= "ml-auto">
      <%= link_to "レシピ一覧に戻る", recipes_path, class: "btn btn-outline-success" %>
    </div>
  </div>
      <div class="info d-flex align-items-center justify-content-center" style="height:600px">
        <h1>料理が存在しません</h1>
      </div>
    </div>
  </div>

<% else %>
<% @sum=0 %>
<div class= "container">
  <div class= "row py-3 px-5">

    <div class= "text-start design">
      <h2 style= "background-color:lightgray">今日の献立</h2>
    </div>
    <div class= "ml-auto">
      <%= link_to "全削除", destroy_all_menus_path, method: :delete, class: "btn btn-outline-danger" %>
    </div>
  </div>

<div class= "container">
  <div class= "row">
    <div class= "col-12 text-start">
      <table class= "table table-bordered">
        <thead style= "color: #FFF; font-weight: bold; background:#00BCD4;">
          <th>商品画像</th>
          <th>食材名</th>
        </thead>
        <tbody>
          <% @menus.each do |menu| %>
          <tr>
            <td class="align-middle "><%= attachment_image_tag @recipe, :image, format: 'jpeg', size: "100x100"%></td>
            <td class="align-middle "><%= menu.recipe.name %></td>
            <td class="align-middle">
              <%= form_with model: @menu, url: menu_path(menu), method: :patch, local: true do |f| %>
                <div>
                  <%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], {selected: menu.quantity}, {class: "col-auto rounded"} %>
                  <%= f.submit "変更",class: "btn btn-outline-dark" %>
                </div>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to "削除する", menu_path(menu.id, menu_id: params[:menu_id]), method: :delete, class: "btn btn-outline-dark" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

        <div class= "row py-3 px-4">
          <div class= "col-sm-6 ">
          　<%= link_to "レシピ一覧に戻る", recipes_path(menu_id: params[:menu_id]), class: "btn btn-outline-dark" %>
        　</div>
        </div>
    </div>
  </div>

  <div class= "row py-3">
    <div class="col-12 text-center">
    <%#= link_to "材料を確定", orders_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <h4 class = "col-3 text-center" style = "background-color:lightgray">レシピ一覧</h4>
  <div class="d-flex flex-wrap">
    <% @recipes.each do |recipe| %>
      <% if recipe.recipe_ings.present? %>
      <div class="mr-3">
        <div class="card">
          <div class="col-xs-3" style="padding-right: 0px; padding-left: 0px;">
            <%= link_to recipe_path(recipe.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
              <%= attachment_image_tag recipe, :image, format: 'jpeg', size: "248x200"%><br>
              <%= recipe.name %><br>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, local:true do |f| %>
  <%= f.label :料理画像 %>
  <%= f.attachment_field :image %>
  <%= f.label :料理名 %>
  <%= f.text_field :name %>
  <%= f.label :説明（工程） %>
  <%= f.text_area :explanation %>
  <%= f.submit "新規登録" %>
<% end %>

app/views/recipes/show.html.erb
<div class="container my-5">
  <div class="row mx-auto">
    <%= attachment_image_tag @recipe, :image, format: "jpeg", fallback: "no_image.jpg", size: "400x300" %>
      <div class="ml-5">
        <h1 class="mt-3"><%= @recipe.name %></h1>
          <p class="h4 mt-2 pb-5"><%= @recipe.explanation %></p>
      </div>
  </div>
</div>
<%= link_to "編集", recipe_ings_path(recipe_id: @recipe), class: 'btn btn-primary' %>
<%= link_to "削除",recipe_path(@recipe), method: :delete, class: "mx-auto btn btn-outline-dark" %>
      <!--  <%#= form_with model: @menu, url: menus_path(current_user), local:true do |f| %>-->
      <!--  <%#= f.hidden_field :user_id, value: current_user.id %>-->
      <!--  <%#= f.hidden_field :recipe_id, value: @recipe.id %>-->
      <!--<div>-->
      <!--  <%#= f.select :quantity, *[1..10] %>-->
      <!--  <%#= f.submit "カートに入れる", class: "btn btn-success" %>-->
      <!--</div>-->
      <%# end %>
  <table class= "table table-bordered">
    <thead style= "color: #FFF; font-weight: bold; background:#00BCD4;">
      <th>商品ID</th>
      <th>食材名</th>
      <th>カロリー</th>
      <th>たんぱく質</th>
      <th>脂質</th>
      <th>炭水化物</th>
      <th>食塩相当量</th>
      <th>ビタミンB1</th>
      <th>ビタミンB2</th>
      <th>ビタミンC</th>
    </thead>
  <tbody>
    <% @recipe_ings.each do |recipe_ing| %>
    <tr>
      <td class="align-middle"><%= recipe_ing.ingredient.id %></td>
      <td class="align-middle"><%= recipe_ing.ingredient.name %></td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_cal %>Kcal</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_protein %>g</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_fat %>g</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_carbon %>g</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_salt %>g</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_vit_b1 %>mg</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_vit_b2 %>mg</td>
      <td class="align-middle"><%= recipe_ing.ingredient.ing_vit_c %>mg</td>
    </tr>
    <% end %>
  </tbody>
</table>

<table class= "table table-bordered">
  <thead style= "color: #FFF; font-weight: bold; background:#32CD32;">
    <th>カロリー</th>
    <th>たんぱく質</th>
    <th>脂質</th>
    <th>炭水化物</th>
    <th>食塩相当量</th>
    <th>ビタミンB1</th>
    <th>ビタミンB2</th>
    <th>ビタミンC</th>
  </thead>
  <tbody>
    <tr>
      <td class="align-middle ">
      <%= @recipe.cal.round(2) if @recipe.cal != nil %>Kcal
    </td>
    <td class="align-middle ">
      <%= @recipe.protein.round(2) if @recipe.protein != nil %>g
    </td>
    <td class="align-middle ">
      <%= @recipe.fat.round(2) if @recipe.fat != nil %>g
    </td>
    <td class="align-middle ">
      <%= @recipe.carbon.round(2) if @recipe.carbon != nil %>g
    </td>
    <td class="align-middle ">
      <%= @recipe.salt.round(2) if @recipe.salt != nil %>g
    </td>
    <td class="align-middle ">
      <%= @recipe.vit_b1.round(2) if @recipe.vit_b1 != nil %>mg
    </td>
    <td class="align-middle ">
      <%= @recipe.vit_b2.round(2) if @recipe.vit_b2 != nil %>mg
    </td>
    <td class="align-middle ">
      <%= @recipe.vit_c.round(2) if @recipe.vit_c != nil %>mg
    </td>
  </tr>
</tbody>


<% if @recipe.favorited_by?(current_user) %>
    <p>
      <%= link_to recipe_favorites_path(@recipe), method: :delete do %>
        ♥<%= @recipe.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to recipe_favorites_path(@recipe), method: :post do %>
        ♡<%= @recipe.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class = "container o-8column">
  <div class = "row">
    <div class = "col-lg-7">

      <div class = "row">
        <h4 class = "col-4 text-center" style = "background-color:lightgray">ユーザー情報の変更</h4>
      </div>
      <%= form_with model:@user, local:true do |f| %>
      <table class = "table table-borderless">

        <tbody>
          <tr class = "row">
            <td class = "col-2">氏名</td>
            <td class = "col-4"><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"姓" %></td>
          </tr>
          <tr class = "row">
            <td class = "col-2"></td>
            <td class = "col-4">
               <div class="form-group">
                 <%= f.submit "編集内容を保存", class: "btn btn-success" %>
               </div>
            </td>
          </tr>
        </tbody>

      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container o-8column">

  <div class = "row">
    <h4 class = "col-3 text-center" style = "background-color:lightgray">マイページ</h4>
  </div>

  <table class = "table table-borderless">
    <tr class = "row">
       <td calss = "col-2"><strong>登録情報</strong></td>
       <td calss = "col-4"><%= link_to '編集する', edit_user_path(@user), class: "btn btn-success" %></td>
     </tr>
  </table>



   <table class = "table table-border-dark" style = "width: 60%;">
     <tbody>
       <tr class = "row">
        <td class = "col-4", style = "background-color:lightgray">氏名</td>
         <td class = "col-8"><%= @user.name %></td>
       </tr>
    </tbody>
  </table>

<%#= link_to recipe.name, ingredients_path(:recipe_id =>recipe.id) %>

    <h5 class = "col-4 mt-5 text-center" style = "background-color:lightgray">材料未確定レシピ</h4>
    <div class="row d-flex flex-wrap">
      <% @recipes.each do |recipe| %>
        <% if !recipe.recipe_ings.present? %>
        <div class="mr-3">
          <div class="card">
            <div class="col-xs-3" style="padding-right: 0px; padding-left: 0px;">
              <%= link_to ingredients_path(:recipe_id =>recipe.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
                <%= attachment_image_tag recipe, :image, format: 'jpeg', size: "248x200"%><br>
                <%= recipe.name %><br>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>

  <div class = "row mt-5">
    <h4 class = "col-3 text-center" style = "background-color:lightgray">リンク</h4>
  </div>

  <div class = "row">
    <!--後日追加予定機能-->
  <%#= link_to '一覧を見る',menus_path(@user), class: "btn btn-primary" %>
    <%= link_to 'レシピ新規作成', new_recipe_path, class: "btn btn-outline-dark"%>
  </div>