config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  resources :recipes do
    resource :favorites, only: [:create, :index, :destroy]
  end

  resources :menus, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "menus/destroy_all" => "menus#destroy_all"

  resources :histories, only:[:index, :show]
  resources :ingredients, only:[:index]

  resources :users, only:[:show, :edit, :update]
  resources :recipe_ings, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "recipe_ings/destroy_all" => "recipe_ings#destroy_all"

end

app/models/recipe_ing.rb
class RecipeIng < ApplicationRecord

  attribute :quantity, :integer,  default: '1'

  belongs_to :user
  belongs_to :ingredient
  belongs_to :recipe

  def sum_of_ing_cal
    ingredient.ing_cal * quantity
  end

  def sum_of_ing_protein
    ingredient.ing_protein * quantity
  end

  def sum_of_ing_fat
    ingredient.ing_fat * quantity
  end

  def sum_of_ing_carbon
    ingredient.ing_carbon * quantity
  end

  def sum_of_ing_salt
    ingredient.ing_salt * quantity
  end

  def sum_of_ing_vit_b1
    ingredient.ing_vit_b1 * quantity
  end

  def sum_of_ing_vit_b2
    ingredient.ing_vit_b2 * quantity
  end

  def sum_of_ing_vit_c
    ingredient.ing_vit_c * quantity
  end
end

app/controllers/recipe_ings_controller.rb
class RecipeIngsController < ApplicationController
   before_action :authenticate_user!

  def index
    @recipe_ings = RecipeIng.where(user_id: current_user.id, recipe_id: params[:recipe_id])
    @recipe = Recipe.find(params[:recipe_id])
    @total_cal = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_cal }
    @total_protein = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_protein }
    @total_fat = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_fat }
    @total_carbon = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_carbon }
    @total_salt = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_salt }
    @total_vit_b1 = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_b1 }
    @total_vit_b2 = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_b2 }
    @total_vit_c = @recipe_ings.inject(0) { |sum, ingredient| sum + ingredient.sum_of_ing_vit_c }
  end

  def create
    recipe_ing = RecipeIng.new
    recipe_ing.user_id = current_user.id
    recipe_ing.recipe_id = params[:recipe_id]
    recipe_ing.ingredient_id = params[:ingredient_id]

    if recipe_ing.save
      redirect_to recipe_ings_path(recipe_id: params[:recipe_id])
    else
      render :index
    end
  end

  def update
    @recipe_ing = RecipeIng.find(params[:id])
    if @recipe_ing.update(quantity: params[:quantity])
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def destroy
    recipe_ing = RecipeIng.find(params[:id])
    recipe_ing.destroy
    redirect_to recipe_ings_path(recipe_id: params[:recipe_id])
  end

  def destroy_all
    current_user.recipe_ings.where(recipe_id: params[:recipe_id]).destroy_all
    redirect_to recipe_ings_path(recipe_id: params[:recipe_id])
  end



  private

  def recipe_ing_params
    # params.permit(:ingredient_id, :recipe_id, :quantity)
    #params.require(:recipe_ing).permit(:ingredient_id, :quantity)
  end
end

app/helpers/recipe_ings_helper.rb
module RecipeIngsHelper
  def calc_nutrition(quantity, nutrition)
    if quantity.present? && nutrition.present?
      (quantity * nutrition).to_s(:delimited)
    else
      "0"
    end
  end
end

app/views/recipe_ings/index.html.erb
<% if !@recipe_ings.present? %>

  <div class="container">
      <div class= "row py-3 px-5">
    <div class= "text-start design">
      <h2 style= "background-color:lightgray">材料確認</h2>
    </div>
    <div class= "ml-auto">
      <%= link_to "材料選択に戻る", ingredients_path(recipe_id: @recipe), class: "btn btn-outline-success" %>
    </div>
  </div>
      <div class="info d-flex align-items-center justify-content-center" style="height:600px">
        <h1>材料が存在しません</h1>
      </div>
    </div>
  </div>

<% else %>
<% @sum=0 %>
<div class= "container">
  <div class= "row py-3 px-5">

    <div class= "text-start design">
      <h2 style= "background-color:lightgray">材料確認</h2>
    </div>
    <div class= "ml-auto">
      <%= link_to "カートを空にする", destroy_all_recipe_ings_path(recipe_id: @recipe.id), method: :delete, class: "btn btn-outline-danger" %>
    </div>
  </div>

<div class= "container">
  <div class= "row">
    <div class= "col-12 text-start">
      <table class= "table table-bordered">
        <thead style= "color: #FFF; font-weight: bold; background:#00BCD4;">
          <th>商品ID</th>
          <th>食材名</th>
          <th>カロリー</th>
          <th>たんぱく質</th>
          <th>脂質</th>
          <th>炭水化物</th>
          <th>食塩相当量</th>
          <th>ビタミンB1</th>
          <th>ビタミンB2</th>
          <th>ビタミンC</th>
        </thead>
        <tbody>
          <% @recipe_ings.each do |recipe_ing| %>
          <tr>
            <td class="align-middle "><%= recipe_ing.ingredient.id %></td>
            <td class="align-middle "><%= recipe_ing.ingredient.name %></td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_cal %>Kcal</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_protein %>g</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_fat %>g</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_carbon %>g</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_salt %>g</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_vit_b1 %>mg</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_vit_b2 %>mg</td>
            <td class="align-middle "><%= recipe_ing.ingredient.ing_vit_c %>mg</td>
            <td class="align-middle">
              <%= form_with model: @recipe_ing, url: recipe_ing_path(recipe_ing), method: :patch, local: true do |f| %>
                <div>
                  <%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], {selected: recipe_ing.quantity}, {class: "col-auto rounded"} %>
                  <%= f.submit "変更",class: "btn btn-outline-dark" %>
                </div>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to "削除する", recipe_ing_path(recipe_ing.id, recipe_id: params[:recipe_id]), method: :delete, class: "btn btn-outline-dark" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <h2 style= "background-color:lightgray">栄養素の合計</h2>
      <%= form_with model: @recipe, method: :patch, local: true do |f| %>
      <table class= "table table-bordered">
        <thead style= "color: #FFF; font-weight: bold; background:#32CD32;">
          <th>カロリー</th>
          <th>たんぱく質</th>
          <th>脂質</th>
          <th>炭水化物</th>
          <th>食塩相当量</th>
          <th>ビタミンB1</th>
          <th>ビタミンB2</th>
          <th>ビタミンC</th>
        </thead>
        <tbody>
          <tr>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_cal) %>
              <%= f.hidden_field :cal, value: @total_cal.to_i %>
              <%= @total_cal.round(2) %>Kcal
            </td>
            <td class="align-middle ">
              <%# calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_protein) %>
              <%= f.hidden_field :protein, value: @total_protein %>
              <%= @total_protein.round(2) %>g
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_fat) %>
              <%= f.hidden_field :fat, value: @total_fat %>
              <%= @total_fat.round(2)%>g
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_carbon) %>
              <%= f.hidden_field :carbon, value: @total_carbon %>
              <%= @total_carbon.round(2)%>g
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_salt) %>
              <%= f.hidden_field :salt, value: @total_salt %>
              <%= @total_salt.round(2)%>g
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_vit_b1) %>
              <%= f.hidden_field :vit_b1, value: @total_vit_b1 %>
              <%= @total_vit_b1.round(2)%>mg
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_vit_b2) %>
              <%= f.hidden_field :vit_b2, value: @total_vit_b2 %>
              <%= @total_vit_b2.round(2)%>mg
            </td>
            <td class="align-middle ">
              <%#= calc_nutrition(recipe_ing.quantity, recipe_ing.ingredient.ing_vit_c) %>
              <%= f.hidden_field :vit_c, value: @total_vit_c %>
              <%= @total_vit_c.round(2)%>mg
            </td>
          </tr>
        </tbody>
      </table>
      <div class= "row py-3">
        <div class="col-12 text-center">
          <%= f.submit "材料を確定", class: "btn btn-success btn-lg" %>
        </div>
  </div>
      <% end %>

        <div class= "row py-3 px-4">
          <div class= "col-sm-6 ">
          　<%= link_to "材料選択に戻る", ingredients_path(recipe_id: params[:recipe_id]), class: "btn btn-outline-dark" %>
        　</div>
        </div>
    </div>
  </div>


</div>

<% end %>