config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  resources :recipes do
    resource :favorites, only: [:create, :index, :destroy]
  end

  resources :menus, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "menus/destroy_all" => "menus#destroy_all"

  resources :histories, only:[:index, :show]
  resources :ingredients, only:[:index]

  resources :users, only:[:show, :edit, :update]
  resources :recipe_ings, only:[:index, :create, :update, :destroy] do
    collection do
      delete "destroy_all"
    end
  end
    delete "recipe_ings/destroy_all" => "recipe_ings#destroy_all"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  has_many :favorite_recipes, through: :favorites, source: 'recipe'

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user, dependent: :destroy

  belongs_to :menu, dependent: :destroy


end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ings, dependent: :destroy
  has_many :recipes
  has_many :histories, dependent: :destroy

end

app/models/menu.rb
class Menu < ApplicationRecord

  attribute :quantity, :integer,  default: '1'

  belongs_to :user
  belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :user

  has_many :menus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_ings, dependent: :destroy
  has_many :ingredints, through: :recipe_ings, source: 'Ingredient'

  has_many :favorite_users, through: :favorites, source: 'User'

  attachment :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recipe_ing.rb
class RecipeIng < ApplicationRecord

  attribute :quantity, :integer,  default: '1'

  belongs_to :user
  belongs_to :ingredient
  belongs_to :recipe

  def sum_of_ing_cal
    ingredient.ing_cal * quantity
  end

  def sum_of_ing_protein
    ingredient.ing_protein * quantity
  end

  def sum_of_ing_fat
    ingredient.ing_fat * quantity
  end

  def sum_of_ing_carbon
    ingredient.ing_carbon * quantity
  end

  def sum_of_ing_salt
    ingredient.ing_salt * quantity
  end

  def sum_of_ing_vit_b1
    ingredient.ing_vit_b1 * quantity
  end

  def sum_of_ing_vit_b2
    ingredient.ing_vit_b2 * quantity
  end

  def sum_of_ing_vit_c
    ingredient.ing_vit_c * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :menus
  has_many :histories, dependent: :destroy
  has_many :user_infos, dependent: :destroy
  has_many :recipe_ings, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :birthday, presence: true

end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes = Recipe.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!

  def index
    @menus = Menu.all
    @history = History.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.user_id = current_user.id

    if current_user.menus.find_by(recipe_id: params[:menu][:recipe_id]).present?
      @menu = current_user.menus.find_by(recipe_id: params[:menu][:recipe_id])
      @menu.quantity += params[:menu][:quantity].to_i
      @menu.save
      redirect_to menus_path

    else
      @menu.save
      redirect_to menus_path
    end
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update(quantity: params[:quantity])
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end


  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_path(menu_id: params[:menu_id])
  end

  private

  def menu_params
    params.require(:menu).permit(:recipe_id, :quantity)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/recipe_ings_helper.rb
module RecipeIngsHelper
  def calc_nutrition(quantity, nutrition)
    if quantity.present? && nutrition.present?
      (quantity * nutrition).to_s(:delimited)
    else
      "0"
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALL-F</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <header>


      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to "ALL-F", root_path, class: "mt-2" %>

          <div>
            <ul class="ml-auto d-flex list-unstyled">
              <% if user_signed_in? %>
                <li class="ml-3">
                  <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-outline-info" %>
                </li>
                <li class="ml-3">
                  <%= link_to "レシピ一覧", recipes_path, class: "btn btn-outline-info" %>
                </li>
                <!--後日追加予定機能-->
                <!--<li class="ml-3">-->
                <!--  <%#= link_to "献立", menus_path, class: "btn btn-outline-info" %>-->
                <!--</li>-->
                <li class="ml-3 mr-1">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-info" %>
                </li>
                <% else %>
                <li class="ml-3">
                  <%= link_to "レシピ一覧", recipes_path, class: "btn btn-outline-info" %>
                </li>
                <li class="ml-3">
                  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-info" %>
                </li>
                <li class="ml-3 mr-1">
                  <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-info" %>
                </li>
              <% end %>
            </ul>
          </div>
          </div>
        </div>
      </nav>
    </header>

  <body>
    <%= yield %>
  </body>
</html>